# encoding: utf-8
source 'https://rubygems.org'

if defined? Encoding
  Encoding.default_external = Encoding::UTF_8
  Encoding.default_internal = Encoding::UTF_8
end

# ruby '2.3.0'

gem 'sinatra', '~> 2.0.0'
gem 'sinatra-contrib', '~> 2.0.0'
gem 'sinatra-flash', '~> 0.3.0'
gem 'sinatra-logger', '~> 0.3.2'
gem 'emk-sinatra-url-for', '~> 0.2.1'

# orm
gem 'mysql2', '~> 0.4.4'
gem 'sinatra-activerecord', '2.0.13'

# cache
gem 'redis', '~> 3.2.2'
gem 'redis-namespace', '~> 1.5.2'
gem 'sidekiq', '~> 4.0.2'

# assets
gem 'json', '~> 1.8.3'
gem 'haml', '~> 4.0.7'
gem 'therubyracer', '~> 0.12.2'
gem 'will_paginate', '~> 3.0.6'
gem 'will_paginate-bootstrap', '~> 1.0.1'

# gem 'puma', '~> 3.4.0'
gem 'unicorn', '~> 5.0.1'
gem 'unicorn-worker-killer', '~> 0.4.4'
gem 'unicorn_metrics', '~> 0.3.1', github: 'superiorlu/unicorn_metrics'

gem 'rake', '~> 12.3.0'
gem 'settingslogic', '~> 2.0.9'
gem 'httparty', '~> 0.13.7'
gem 'faraday', '~> 0.9.2'
gem 'rack-mini-profiler', '~> 0.9.9.2'
gem 'ruby-pinyin', '~> 0.5.0'
gem 'get_process_mem', '~> 0.2.0'
gem 'rubyzip', '~> 1.2.0'
gem 'geetest3', '~> 0.1.0'
gem 'terminal-table', '~> 1.8.0'

# gem 'device_detector'
# gem 'exception_notification', '~> 4.1.3'

group :development do
  # deploy
  gem 'sshkit', github: 'capistrano/sshkit'
  gem 'capistrano', '~> 3.6.1'
  gem 'capistrano-bundler', '~> 1.1.4'
  gem 'capistrano-rbenv', '~> 2.0.4'
  # kit tool
  gem 'nokogiri', '~> 1.6.7.2', require: false
  gem 'whenever'
  gem 'pry', '~> 0.10.3'
  gem 'net-ssh', '~> 2.8.0'
  gem 'net-scp', '~> 1.2.1'
  gem 'guard-livereload', '~> 2.5.2', require: false
  # code style optimized
  gem 'rubycritic', '~> 2.8.0', require: false
  gem 'rubocop', '~> 0.38.0', require: false
  gem 'jshintrb', '~> 0.3.0'
  gem 'fasterer', '~> 0.3.2'
  gem "qiniu", "~> 6.3.2"
end

return unless `uname -s`.strip.eql?('Darwin')

group :test do
  gem 'rack-test', '~> 0.6.3'
  gem 'rspec', '~> 3.7.0'
  gem 'rspec-sidekiq', '~> 3.0.3'
  gem 'factory_girl', '~> 4.5.0'
  gem 'capybara', '~> 2.6.2'
  gem 'poltergeist', '~> 1.9.0'
  gem 'database_cleaner', '~> 1.5.3'
  gem 'simplecov', '~> 0.11.2', require: false
end
