# encoding: utf-8
source 'https://rubygems.org'

if defined? Encoding
  Encoding.default_external = Encoding::UTF_8
  Encoding.default_internal = Encoding::UTF_8
end

gem 'rake', '~> 12.3.0'
gem 'settingslogic', '~> 2.0.9'
gem 'httparty', '~> 0.13.7'
gem 'faraday', '~> 0.9.2'
gem 'ruby-pinyin', '~> 0.5.0'
gem 'terminal-table', '~> 1.8.0'

gem 'net-ssh', '~>4.2.0'
gem 'net-scp', '~>1.2.1'

