# encoding: utf-8
source 'https://rubygems.org'

if defined? Encoding
  Encoding.default_external = Encoding::UTF_8
  Encoding.default_internal = Encoding::UTF_8
end

gem 'rake', '~> 12.3.0'
gem 'rest-client', '~> 2.0.2'
gem 'terminal-table', '~> 1.8.0'
gem 'httparty', '~> 0.13.7' # todo: remove

if File.exists?("local-sypctl-server")
  gem 'sinatra', '~> 2.0.0'
  gem 'sinatra-contrib', '~> 2.0.0'
  gem 'unicorn', '~> 5.0.1'
  gem 'unicorn-worker-killer', '~> 0.4.4'
  gem 'json', '~> 1.8.3'
  gem 'haml', '~> 4.0.7'
end

if `uname -s`.strip == 'Darwin'
  gem 'net-ssh', '~>4.2.0'
  gem 'net-scp', '~>1.2.1'
end

