#!/usr/bin/env rake
require 'rubygems'

class String
  # Strips indentation in heredocs.
  #
  # For example in
  #
  #   if options[:usage]
  #     puts <<-USAGE.strip_heredoc
  #       This command does such and such.
  #
  #       Supported options are:
  #         -h         This message
  #         ...
  #     USAGE
  #   end
  #
  # the user would see the usage message aligned against the left margin.
  #
  # Technically, it looks for the least indented non-empty line
  # in the whole string, and removes that amount of leading whitespace.
  def strip_heredoc
    gsub(/^#{scan(/^[ \t]*(?=\S)/).min}/, "".freeze).tap do |stripped|
      stripped.freeze if frozen?
    end
  end
end

task default: [:environment]

desc 'bundle exec rake task_name RACK_ENV=development'
task environment: 'Gemfile.lock' do
  ENV['RACK_ENV'] ||= 'production'
  ENV['RAILS_ENV'] = ENV['RACK_ENV']
  begin
    ENV['BUNDLE_GEMFILE'] ||= "./Gemfile"
    require 'rake'
    require 'bundler'
    Bundler.setup
  rescue => e
    puts e.backtrace && exit
  end
  Bundler.require(:default, ENV['RACK_ENV'])
end

Dir.glob('tasks/*.rake') do |filepath|
  load filepath
end
