#!/usr/bin/env rake
require 'rubygems'

ENV["SYPCTL-VERSION"] = "0.0.35"
ENV["SYPCTL-API"] = "http://sypctl-api.idata.mobi"
ENV['RAKE_ROOT_PATH'] = File.dirname(__FILE__)

$LOAD_PATH.unshift(ENV['RAKE_ROOT_PATH'])
$LOAD_PATH.unshift(%(#{ENV['RAKE_ROOT_PATH']}/config))
$LOAD_PATH.unshift(%(#{ENV['RAKE_ROOT_PATH']}/lib/tasks))

require 'lib/core_ext/string.rb'
require 'lib/core_ext/numberic.rb'
require 'lib/utils/rake_instance_methods.rb'

task default: [:environment]

desc 'bundle exec rake task_name RACK_ENV=development'
task environment: 'Gemfile.lock' do
  ENV['RACK_ENV'] ||= 'production'
  ENV['RAILS_ENV'] = ENV['RACK_ENV']
  begin
    ENV['BUNDLE_GEMFILE'] ||= "./Gemfile"
    require 'rake'
    require 'bundler'
    Bundler.setup
  rescue => e
    puts e.backtrace && exit
  end
  Bundler.require(:default, ENV['RACK_ENV'])
end

Dir.glob('tasks/*.rake') do |filepath|
  load filepath
end
